import {
  AlertTriangle,
  ArrowRight,
  Ban,
  Bot,
  CircleAlert,
  Flame,
  Minus,
  User,
} from 'lucide-react';
import { cn } from '@/lib/utils';
import type { EscalationBriefingDto } from '@/lib/contract';

/**
 * Agent handover briefing.
 *
 * Rendered when a chat escalates to `human_pending_flag`. The briefing is
 * generated by the BE at the moment of escalation (see
 * `src/ai/settings/escalation.js`), so unlike the running conversation
 * summary it always reflects the message that actually caused the handoff.
 *
 * Layout is deliberately not a uniform card grid: an agent picking this up
 * cold reads top-to-bottom and needs the headline and the next action to
 * dominate. The middle fields are supporting detail and are typeset as
 * such.
 */

type Sentiment = NonNullable<EscalationBriefingDto['sentiment']>;

const SENTIMENT: Record<
  Sentiment,
  { label: string; icon: typeof Minus; className: string }
> = {
  neutral: {
    label: 'Netral',
    icon: Minus,
    className: 'bg-muted text-muted-foreground border-border',
  },
  frustrated: {
    label: 'Kecewa',
    icon: CircleAlert,
    // Icon + label carry the meaning; colour is reinforcement only.
    className: 'bg-warning/10 text-warning border-warning/30',
  },
  urgent: {
    label: 'Mendesak',
    icon: Flame,
    className: 'bg-destructive/10 text-destructive border-destructive/30',
  },
};

const REASON_LABEL: Record<string, string> = {
  confidence_low: 'Confidence rendah',
  fallback_handoff: 'AI pakai fallback',
  ungrounded_number: 'Angka tidak tergrounding',
  turbo_cutoff: 'Retrieval di bawah cutoff',
  parse_failure: 'Output tidak bisa di-parse',
};

function SentimentChip({ sentiment }: { sentiment: Sentiment }) {
  const s = SENTIMENT[sentiment] ?? SENTIMENT.neutral;
  const Icon = s.icon;
  return (
    <span
      className={cn(
        'inline-flex shrink-0 items-center gap-1 rounded-full border px-2 py-0.5 text-xs font-medium',
        s.className
      )}
    >
      <Icon aria-hidden className="h-3 w-3" />
      {s.label}
    </span>
  );
}

/** One labelled line of supporting detail. Renders nothing when empty. */
function Field({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Bot;
  label: string;
  value?: string | null;
}) {
  if (!value || !value.trim()) return null;
  return (
    <div className="flex gap-2.5">
      <Icon aria-hidden className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" />
      <div className="min-w-0 space-y-0.5">
        <dt className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
          {label}
        </dt>
        <dd className="text-sm leading-relaxed text-foreground">{value}</dd>
      </div>
    </div>
  );
}

export interface EscalationBriefingProps {
  briefing: EscalationBriefingDto;
  /** Escalation timestamp (epoch seconds); rendered by the caller if shown. */
  className?: string;
}

export function EscalationBriefing({ briefing, className }: EscalationBriefingProps) {
  const sentiment: Sentiment = briefing.sentiment ?? 'neutral';
  const reason = briefing.reason ?? undefined;
  const reasonLabel = reason ? (REASON_LABEL[reason] ?? reason) : null;

  const hasBody =
    !!briefing.customer_wants?.trim() ||
    !!briefing.ai_attempted?.trim() ||
    !!briefing.blocking_gap?.trim();

  return (
    <section
      aria-label="Ringkasan serah terima"
      data-testid="escalation-briefing"
      className={cn(
        'rounded-lg border border-warning/30 bg-warning/[0.06] p-4',
        className
      )}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="flex min-w-0 items-start gap-2.5">
          <AlertTriangle
            aria-hidden
            className="mt-0.5 h-4 w-4 shrink-0 text-warning"
          />
          <div className="min-w-0">
            <h3 className="text-sm font-semibold leading-snug text-foreground">
              {briefing.headline?.trim() || 'Chat dialihkan ke agent'}
            </h3>
            <div className="mt-1 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
              {reasonLabel && <span>{reasonLabel}</span>}
              {typeof briefing.confidence === 'number' && (
                <>
                  {reasonLabel && <span aria-hidden>·</span>}
                  <span>confidence {briefing.confidence.toFixed(2)}</span>
                </>
              )}
            </div>
          </div>
        </div>
        <SentimentChip sentiment={sentiment} />
      </div>

      {hasBody && (
        <dl className="mt-4 space-y-3 border-t border-warning/20 pt-3">
          <Field icon={User} label="Pelanggan minta" value={briefing.customer_wants} />
          <Field icon={Bot} label="Yang AI coba" value={briefing.ai_attempted} />
          <Field icon={Ban} label="Yang menghambat" value={briefing.blocking_gap} />
        </dl>
      )}

      {briefing.suggested_next_action?.trim() && (
        <div className="mt-4 flex gap-2.5 rounded-md border border-border bg-card p-3">
          <ArrowRight aria-hidden className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
          <div className="min-w-0">
            <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
              Langkah berikutnya
            </p>
            <p className="mt-0.5 text-sm font-medium leading-relaxed text-foreground">
              {briefing.suggested_next_action}
            </p>
          </div>
        </div>
      )}

      {/* The model's own account of why it stopped. Collapsed because it is
          diagnostic detail, not something the agent needs to act on. */}
      {briefing.ai_reasoning?.trim() && (
        <details className="group mt-3">
          <summary className="cursor-pointer list-none text-xs font-medium text-muted-foreground underline-offset-2 hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-1 rounded">
            <span className="group-open:hidden">Lihat alasan AI</span>
            <span className="hidden group-open:inline">Sembunyikan alasan AI</span>
          </summary>
          <p className="mt-2 border-l-2 border-border pl-3 text-xs leading-relaxed text-muted-foreground">
            {briefing.ai_reasoning}
          </p>
        </details>
      )}

      {briefing.degraded && (
        <p className="mt-3 text-xs text-muted-foreground">
          Ringkasan otomatis tidak tersedia saat eskalasi — tampilkan pesan terakhir
          di bawah untuk konteks.
        </p>
      )}
    </section>
  );
}
